// GENERATED by scripts/ops/attest-identity.ts. Do not edit by hand.
//
// ⚠️ **Two signatures over one sentence, and they are the only part of the report-to-stake binding
// that is not otherwise readable off a public chain.** Anyone can `ethers.verifyMessage(message, …)`
// each one and watch it recover the address it claims. Nothing here needs our word for it.
//
// ⚠️ **Committed, on purpose, rather than put in the database.** A verifier is a stranger with this
// repo and two public RPCs; a row in our Neon instance would be checkable only by us, which is the
// problem this file exists to remove. It also needs no migration and no network to read.
//
// ⚠️ **If either key ever changes this file is VOID and must be regenerated.** The Arc key is the
// harder half: `AlphaMarket`'s `resolver` is immutable with no setter, so a new Arc key means a new
// contract, not a reconfigured one — which is the same thing this project says everywhere else about
// analyst identity. A lost key is a new analyst.
//
// ⚠️ `producedAt` is OUTSIDE the signed bytes. It is provenance, not a claim either key made.

import { type IdentityAttestation } from './identity.js';

export const ANALYST_ATTESTATION: IdentityAttestation = {
  "schema": "alpha-markets/identity-attestation/v1",
  "analyst": "alpha-1",
  "arcAddress": "0x1b7035bbe0da8f3bcb721863d42e1079e4a116a7",
  "hederaEvmAddress": "0x32838fe90541567bbf77fa0570661f3c20e2b152",
  "hederaAccountId": "0.0.10387690",
  "message": "alpha-markets/identity-attestation/v1\n\nanalyst:          alpha-1\narc address:      0x1b7035bbe0da8f3bcb721863d42e1079e4a116a7   (chain 5042002)\nhedera address:   0x32838fe90541567bbf77fa0570661f3c20e2b152   (chain 296)\nhedera account:   0.0.10387690\n\nThese two addresses are one analyst. The Arc address commits predictions and stakes its own\nUSDC on them; the Hedera address issues the report tokens those predictions cite. This message\nis signed by both keys, so each address vouches for the other.",
  "arcSignature": "0xdd4f3b5ab384b08413d65e5126812468a6ad61495c5250a1b907c2e65cb68e3d3ff04ac68d4825b8d5a475879d04ddc64af8bcd5f09ebe4b4d003c79b6b1f02a1b",
  "hederaSignature": "0x34e291ee329a37a4e5150b7e83ee94fe7cac3cde2b34931d998e4f6d6f56db8f0a743c1980c87170792622a22b18852b9858dc03460823d671a42776d155c61f1c",
  "producedAt": "2026-09-11T06:10:59.309Z"
};
