// Unit 6b — produce the two-way key attestation, then prove it recovers.
//
//   npx tsx --env-file=.env scripts/ops/attest-identity.ts           produce (signs) then verify
//   npx tsx --env-file=.env scripts/ops/attest-identity.ts --check   verify only, never signs
//   npx tsx --env-file=.env scripts/ops/attest-identity.ts --force   re-sign over an existing one
//
// ⚠️ **Produced once, forever.** Without `--force` this refuses to re-sign an attestation that
// already verifies — the claim is permanent and a second signature over the same sentence would be
// new bytes asserting nothing new. `build-contract.ts` is the pattern: produce an artifact, commit
// it, and keep a check mode that needs no credentials to run.
//
// ⚠️ **Signing is NOT a transaction.** `POST /v1/w3s/developer/sign/message` returns a signature,
// not a transaction id — no fee field, no `TransactionState`, nothing to wait for. This script
// confirms that empirically by reading the analyst's Arc balance either side of the call rather
// than taking the API shape's word for it.

import { writeFileSync } from 'node:fs';
import { ethers } from 'ethers';
import {
  ATTESTATION_SCHEMA, type IdentityAttestation, attestationMessage, signAsArc, signAsHedera,
  verifyAttestation,
} from '../../src/arc/identity.js';
import { arcProvider } from '../../src/arc/arc.js';
import { ANALYSTS } from '../../src/config/analysts.js';

const CHECK_ONLY = process.argv.includes('--check');
const FORCE = process.argv.includes('--force');
const OUT = new URL('../../src/arc/attestation.ts', import.meta.url);

let failures = 0;
const ok = (label: string, condition: boolean, detail = ''): void => {
  console.log(`  ${condition ? '✅' : '❌'} ${label}${detail ? `   ${detail}` : ''}`);
  if (!condition) failures += 1;
};

const analyst = ANALYSTS[0]!;
const message = attestationMessage(analyst);

console.log(`\n── the sentence both keys sign\n`);
console.log(message.split('\n').map((l) => `     ${l}`).join('\n'));

// ── Load whatever already exists, without requiring it to ────────────────────────────────────────
//
// ⚠️ Imported by runtime URL rather than by a literal specifier, because on the FIRST run the file
// does not exist yet and a static import of it would not typecheck. Every other reader of the
// attestation imports it normally — this is the one place with a bootstrap problem.
let existing: IdentityAttestation | null = null;
try {
  const loaded = await import(OUT.href) as { ANALYST_ATTESTATION: IdentityAttestation };
  existing = loaded.ANALYST_ATTESTATION;
} catch { /* not produced yet — the first run is the produce run */ }

let attestation: IdentityAttestation;

if (existing && !FORCE) {
  console.log('\n── already produced — verifying rather than re-signing');
  attestation = existing;
} else if (CHECK_ONLY) {
  console.error('\nSTOP  --check but src/arc/attestation.ts does not exist. Run without --check to produce it.\n');
  process.exit(1);
} else {
  console.log('\n── signing (live: one Circle API call, one local key)');
  const provider = arcProvider();

  // ⚠️ Confirmed, not assumed. If signMessage were a transaction this number would move.
  const before = await provider.getBalance(analyst.arcAddress);
  const arcSignature = await signAsArc(message);
  const after = await provider.getBalance(analyst.arcAddress);
  ok('Circle signMessage spent NO gas', before === after,
    `${ethers.formatUnits(before, 18)} USDC, unchanged`);

  const hederaSignature = await signAsHedera(message, analyst);

  attestation = {
    schema: ATTESTATION_SCHEMA,
    analyst: analyst.id,
    arcAddress: analyst.arcAddress,
    hederaEvmAddress: analyst.hederaEvmAddress,
    hederaAccountId: analyst.hederaAccountId,
    message,
    arcSignature,
    hederaSignature,
    producedAt: new Date().toISOString(),
  };

  const header = `// GENERATED by scripts/ops/attest-identity.ts. Do not edit by hand.
//
// ⚠️ **Two signatures over one sentence, and they are the only part of the report-to-stake binding
// that is not otherwise readable off a public chain.** Anyone can \`ethers.verifyMessage(message, …)\`
// each one and watch it recover the address it claims. Nothing here needs our word for it.
//
// ⚠️ **Committed, on purpose, rather than put in the database.** A verifier is a stranger with this
// repo and two public RPCs; a row in our Neon instance would be checkable only by us, which is the
// problem this file exists to remove. It also needs no migration and no network to read.
//
// ⚠️ **If either key ever changes this file is VOID and must be regenerated.** The Arc key is the
// harder half: \`AlphaMarket\`'s \`resolver\` is immutable with no setter, so a new Arc key means a new
// contract, not a reconfigured one — which is the same thing this project says everywhere else about
// analyst identity. A lost key is a new analyst.
//
// ⚠️ \`producedAt\` is OUTSIDE the signed bytes. It is provenance, not a claim either key made.

import { type IdentityAttestation } from './identity.js';

export const ANALYST_ATTESTATION: IdentityAttestation = ${JSON.stringify(attestation, null, 2)};
`;
  writeFileSync(OUT, header);
  console.log(`  wrote src/arc/attestation.ts`);
}

// ── The proof. ⚠️ ethers.verifyMessage only — never a helper this unit wrote ──────────────────────

console.log('\n── recovery, run with ethers.verifyMessage so the check is not the thing being checked');

const arcRecovered = ethers.verifyMessage(attestation.message, attestation.arcSignature);
const hederaRecovered = ethers.verifyMessage(attestation.message, attestation.hederaSignature);
console.log(`     arc signature    recovers ${arcRecovered}`);
console.log(`     hedera signature recovers ${hederaRecovered}`);

ok('arc signature recovers the Arc address', arcRecovered.toLowerCase() === analyst.arcAddress.toLowerCase());
ok('hedera signature recovers the Hedera address', hederaRecovered.toLowerCase() === analyst.hederaEvmAddress.toLowerCase());
ok('the two recover DIFFERENT addresses', arcRecovered.toLowerCase() !== hederaRecovered.toLowerCase());

// ⚠️ The module's own verifier, checked against the independent recovery above rather than trusted.
const verdict = verifyAttestation(attestation, analyst);
ok('verifyAttestation() agrees on both', verdict.arc && verdict.hedera);
ok('the stored message matches the analyst row', verdict.messageMatchesRow);

console.log('\n── what must fail, and does');

// ⚠️ One character. A signature is over a hash, so any edit at all moves the recovered address to
// some unrelated key rather than failing loudly — which is why this asserts the address, not an error.
const tampered = attestation.message.replace(analyst.arcAddress, '0x' + 'de'.repeat(20));
ok('a tampered message does not recover the Arc address',
  ethers.verifyMessage(tampered, attestation.arcSignature).toLowerCase() !== analyst.arcAddress.toLowerCase());

// ⚠️ THE CHECK THAT MATTERS MOST. If a signature verified against either address, the attestation
// would prove one key exists twice rather than two keys agreeing.
ok('the arc signature does NOT recover the Hedera address',
  ethers.verifyMessage(attestation.message, attestation.arcSignature).toLowerCase() !== analyst.hederaEvmAddress.toLowerCase());
ok('the hedera signature does NOT recover the Arc address',
  ethers.verifyMessage(attestation.message, attestation.hederaSignature).toLowerCase() !== analyst.arcAddress.toLowerCase());

const swapped: IdentityAttestation = {
  ...attestation, arcSignature: attestation.hederaSignature, hederaSignature: attestation.arcSignature,
};
const swappedVerdict = verifyAttestation(swapped, analyst);
ok('swapping the two signatures fails BOTH', !swappedVerdict.arc && !swappedVerdict.hedera);

// ⚠️ A signature is 65 bytes and recovery does not fail on garbage — it returns *a* key. Truncation
// is the case that does throw, and `verifyAttestation` must survive it rather than crash a verifier.
ok('a malformed signature is refused rather than thrown',
  verifyAttestation({ ...attestation, arcSignature: '0xdeadbeef' }, analyst).arc === false);

console.log(failures === 0
  ? `\nPASS  both keys attest to one analyst.${CHECK_ONLY ? ' (check only — nothing signed)' : ''}\n`
  : `\nFAIL  ${failures} check(s).\n`);
process.exit(failures === 0 ? 0 : 1);
